// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6jYDidfOpLVsu2t6h7Jlss_hm8vyVRB4',
    appId: '1:766521297013:web:a326c2a1f0ad9598a6d03c',
    messagingSenderId: '766521297013',
    projectId: 'eduapp-e3e7d',
    authDomain: 'eduapp-e3e7d.firebaseapp.com',
    storageBucket: 'eduapp-e3e7d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwhPYmhg6q0YIx0WLO4NKY0d5rQwXig4M',
    appId: '1:766521297013:android:4acc2c1e94df85b4a6d03c',
    messagingSenderId: '766521297013',
    projectId: 'eduapp-e3e7d',
    storageBucket: 'eduapp-e3e7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtalrOhRRnukLaPI34oGYTLc3uStcXe9Q',
    appId: '1:766521297013:ios:268866ad026aa7b5a6d03c',
    messagingSenderId: '766521297013',
    projectId: 'eduapp-e3e7d',
    storageBucket: 'eduapp-e3e7d.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtalrOhRRnukLaPI34oGYTLc3uStcXe9Q',
    appId: '1:766521297013:ios:268866ad026aa7b5a6d03c',
    messagingSenderId: '766521297013',
    projectId: 'eduapp-e3e7d',
    storageBucket: 'eduapp-e3e7d.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6jYDidfOpLVsu2t6h7Jlss_hm8vyVRB4',
    appId: '1:766521297013:web:2ef497f07188b049a6d03c',
    messagingSenderId: '766521297013',
    projectId: 'eduapp-e3e7d',
    authDomain: 'eduapp-e3e7d.firebaseapp.com',
    storageBucket: 'eduapp-e3e7d.firebasestorage.app',
  );
}